#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
# Temporarily disable check of external links as too many are failing
# FIXME: enable external link checking
bundle exec htmlproofer --check-html --disable-external --log-level debug ./_site
