# Please keep this file in reverse chronological order:
# Newest things go on top!
- title: Software Training in HEP
  date: 2021-02-28
  url: https://arxiv.org/abs/2103.00659
  type: paper
  note: Submitted to CSBS.
- title: Software Training and Sustainable HEP
  date: 2021-06-29
  url: https://indico.cern.ch/event/1004432/contributions/4377762/
  type: talk
  note: Video available
- title: Software Training in HEP
  date: 2021-05-21
  type: talk
  note: Video available
- title: Community building
  date: 2020-11-19
  url: https://indico.cern.ch/event/941278/contributions/4084356/
  type: talk
  note: Video available
- title: 'HSF Training: Making "that thing my postdoc taught me once" available for everyone'
  date: 2020-11-19
  url: https://indico.cern.ch/event/941278/contributions/4084355/
  type: talk
  note: Video available
- title: 'HEP Software Foundation Community White Paper Working Group - Training, Staffing and Careers'
  date: 2018-07-08
  type: paper
  note: null