#!/usr/bin/env bash

usage () {
    echo "usage: $(basename $0) [--debug]"
    exit 2
}

debug_option=

if [ "$1" == "--debug" ]
then
    debug_option="--log-level debug"
elif [ -n "$1" ]
then
    echo "Unsupported option ($1)"
    usage
fi

# Update certificates
sudo -u root $(dirname $0)/install-certs.sh

export LD_LIBRARY_PATH=$(pwd)/.travis-scripts/lib:$LD_LIBRARY_PATH

bundle exec jekyll build
bundle exec htmlproofer ${url_ignore_option} ${debug_option} --check-html ./_site
status=$?
if [ ${status} -ne 0 -a -z "${debug_option}" ]
then
    echo ""
    echo "htmlproofer failed to validate site contents: use --debug for more information"
fi

exit ${status}
