@
name: Lighthouse CI
on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build Jekyll Site
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@12.1.0
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
@
