name: link_checker

on: [push, pull_request]

jobs:
  check_new_links:
    name: link_checker
    runs-on: ubuntu-latest
    env:
      # Allow the old version of node to run, pending a proper fix
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  
    container: hepsoftwarefoundation/hsf-jekyll
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: jekyll build
        run: |
          bundler exec jekyll build

      - name: actions link checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/config/mdcheck.json'
          check-modified-files-only: 'yes'
          use-verbose-mode: 'yes'
          base-branch: 'main'
